# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path
name: Build

on:
  # It triggers the workflow when executing the push or pull request operation, but only for the master branch.
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml.
          settings-path: ${{ github.workspace }} # Location for the settings.xml file.

      - name: Configure GIT
        run: |
          git config --global committer.email "noreply@github.com"
          git config --global committer.name "GitHub"
          git config --global author.email "${{ github.actor }}@users.noreply.github.com"
          git config --global author.name "${{ github.actor }}"

      - name: Cache Maven Repository
        uses: actions/cache@v1
        env:
          cache-name: m2-repository
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-cache-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-cache-${{ env.cache-name }}-
            ${{ runner.os }}-cache-
            ${{ runner.os }}-

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Create Tag Version
        run: mvn scm:tag -Dusername=${{ github.actor }} -Dpassword=${{ github.token }}

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -Dmaven.test.skip=true -s ${{ github.workspace }}/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Push Build Status Notifications
        if: ${{ always() }}
        uses: desiderati/github-action-pushover@v1
        with:
          job-status: ${{ job.status }}
          pushover-api-token: ${{ secrets.PUSHOVER_API_TOKEN }}
          pushover-user-key: ${{ secrets.PUSHOVER_USER_KEY }}
